### ISSUE TITLE
no support for device type power_supply

### ISSUE THREAD

**Issue by stugol** [richrd/suplemon#110]
When I run the editor, I get the following confusing message in the text, overwriting anything already there:

``no support for device type power_supply``

Also the following errors on the command line after I exit the editor:
```
2016-01-07 03:41:50,393 - root - INFO - Starting Suplemon...                           @ 0,3 cur:1 buf:0 cs:4 hist:5
2016-01-07 03:41:50,404 - suplemon.config - INFO - Configuration file '/home/infinity/.config/suplemon/suplemon-config.json' doesn't exist.
2016-01-07 03:41:50,404 - suplemon.config - WARNING - Failed to load config file!
2016-01-07 03:41:50,407 - suplemon.modules - INFO - Loading modules...
2016-01-07 03:41:50,423 - module.system_clipboard - WARNING - xsel not available. Can't use system clipboard.
2016-01-07 03:41:50,432 - suplemon.ui - INFO - Loading UI for terminal: xterm-256color
2016-01-07 03:41:50,433 - suplemon.themes - INFO - Loading theme monokai
2016-01-07 03:41:50,439 - suplemon.viewer - INFO - Pygments not available, please install it for proper syntax highlighting.
2016-01-07 03:41:50,439 - suplemon.viewer - INFO - Pygments not available, please install it for proper syntax highlighting.
2016-01-07 03:42:02,937 - root - ERROR - Failed running callback: <bound method Linter.mainloop of <linter.Linter object at 0x7fe10c37c828>>
Traceback (most recent call last):
  File "/home/infinity/suplemon/suplemon/main.py", line 447, in trigger_event
    val = cb(event)
  File "/home/infinity/suplemon/suplemon/modules/linter.py", line 41, in mainloop
    msg = self.get_msgs_on_line(editor, cursor.y)
  File "/home/infinity/suplemon/suplemon/modules/linter.py", line 86, in get_msgs_on_line
    line = editor.lines[line_no]
IndexError: list index out of range
2016-01-07 03:42:03,321 - root - ERROR - Failed running callback: <bound method Linter.mainloop of <linter.Linter object at 0x7fe10c37c828>>
Traceback (most recent call last):
  File "/home/infinity/suplemon/suplemon/main.py", line 447, in trigger_event
    val = cb(event)
  File "/home/infinity/suplemon/suplemon/modules/linter.py", line 41, in mainloop
    msg = self.get_msgs_on_line(editor, cursor.y)
  File "/home/infinity/suplemon/suplemon/modules/linter.py", line 86, in get_msgs_on_line
    line = editor.lines[line_no]
IndexError: list index out of range
```

This does not fill me with confidence. It does, however, prevent me from using the program.

**Comment by richrd** [comment]
Sorry for the late response! This somehow went under my radar.

I'll fix this ASAP and get back soon!

**Comment by richrd** [comment]
BTW, what platform and terminal are you using?

**Comment by richrd** [comment]
Hi! I managed to reproduce and fix this. Thanks a lot for the report! :+1:

Could you pull v0.1.44 from master and confirm it's working?

**Comment by stugol** [comment]
I'm using Debian Jessie 64-bit, with Zsh. I'll give the new version a try, thanks.

**Comment by stugol** [comment]
What is meant by "suplemon.viewer - INFO - Pygments not available, please install it for proper syntax highlighting"? Which package should I install to fix this?

"python-pygments" is already installed.

**Comment by richrd** [comment]
Pygments is used for syntax highlighting code in the editor. To get it working you need the `python3-pygments` package. The `python-pygments` is the Python 2 version.

**Comment by stugol** [comment]
Ah, righty ho. Might I suggest adding something helpful to the error message? "Install python3-pygments" for instance?

**Comment by stugol** [comment]
Can I add a keyboard shortcut to the config for "exit with save prompt", a la nano?

**Comment by richrd** [comment]
Yeah, not a bad idea. I'll improve the error message about Pygments.

Unfortunately there currently isn't a command for both saving and exiting at the same time. I feel it might be a bit redundat since it's quite quick to hit `Ctrl+S` and `Ctrl+Q`. Anyway I'll think about it more and maybe implement it if there's enough demand :+1: 

Just to make sure: is your original issue resolved? Feel free to add more issues and feature requests if you have any :)

**Comment by stugol** [comment]
Yup, it's working fine thanks.

I think the save-exit feature would be very useful.
