### ISSUE TITLE
Errors to close the file

### ISSUE THREAD

**Issue by arenasgt** [richrd/suplemon#178]
I just started to using this tool I like it thanks and after I close a file I got these errors:
i am running OS X yosemite.

"""
 $suplemon foo.py
2017-02-15 21:24:41,258 - suplemon.config - INFO - Failed to load config file '/Users/Jass/.config/suplemon/suplemon-config.json'.
2017-02-15 21:24:41,287 - suplemon.module_loader - ERROR - Initializing module failed: hostname
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/suplemon/module_loader.py", line 47, in load_instance
    inst = module[1]["class"](self.app, module[0], module[1])  # Store the module instance
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/suplemon/suplemon_module.py", line 111, in __init__
    self.init()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/suplemon/modules/hostname.py", line 12, in init
    hostinfo = socket.gethostbyaddr(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
2017-02-15 21:24:41,304 - module.system_clipboard - WARNING - Can't use system clipboard. Install 'xsel' for system clipboard support.
2017-02-15 21:24:41,369 - suplemon.file - INFO - Given path isn't a file.
"""

**Comment by richrd** [comment]
Hi! Thanks for reporting this.

It's normal that suplemon prints some messages like INFO and WARNING, those are nothing to worry about, but the ERROR you got shouldn't happen. Suplemon has a plugin that shows the machines hostname in the bottom right corner to remind you what server you're working on. Apparently it's failing to detect the hostname. I'll get this fixed in the next release.

**Comment by richrd** [comment]
The error should be fixed now, but it seems like there's something wrong in your `suplemon-config.json` file. Could you paste the contents here so I can check it for you? If you want to disable all the debug messages you could put the following in your config: 

```
{
    "app": {
        "debug": 0
    }
}
```

"""
$suplemon foo.py
2017-02-15 21:24:41,258 - suplemon.config - INFO - Failed to load config file '/Users/Jass/.config/suplemon/suplemon-config.json'.
2017-02-15 21:24:41,304 - module.system_clipboard - WARNING - Can't use system clipboard. Install 'xsel' for system clipboard support.
2017-02-15 21:24:41,369 - suplemon.file - INFO - Given path isn't a file.
"""

**Comment by arenasgt** [comment]
I updated  to 0.1.59 and this are the errors:

"""
$ suplemon project_name.py
2017-02-17 15:13:17,787 - suplemon.config - INFO - Failed to load config file '/Users/Jass/.config/suplemon/suplemon-config.json'.
2017-02-17 15:13:17,815 - suplemon.module_loader - ERROR - Initializing module failed: hostname
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/suplemon/module_loader.py", line 47, in load_instance
    inst = module[1]["class"](self.app, module[0], module[1])  # Store the module instance
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/suplemon/suplemon_module.py", line 112, in __init__
    self.init()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/suplemon/modules/hostname.py", line 15, in init
    hostinfo = socket.gethostbyaddr(socket.gethostname())
socket.herror: [Errno 1] Unknown host
2017-02-17 15:13:17,833 - module.system_clipboard - WARNING - Can't use system clipboard. Install 'xsel' for system clipboard support.
2017-02-17 15:13:23,907 - suplemon.file - INFO - Given path isn't a file.
"""

my config opened with (ctrl-e>config)
""" 
 ⚈ Suplemon Editor v0.1.59 - ⌚15:16 17.02. [suplemon-config.json]
1 {
2 ›   "app": {
3 ›   ›   "debug": 0
4 ›   }
5 }

"""

After I added this the errors went away.
cheers,

**Comment by richrd** [comment]
Good that you got rid of the debug messages. The error in question isn't anything to worry about. 

Apparently my error handling wasn't broad enough to catch the new error you got, will fix.
