### ISSUE TITLE
_curses.error

### ISSUE THREAD

**Issue by shakna-israel** [richrd/suplemon#51]
Trying to run suplemon causes an instant crash on Python 3.2.3:

```python3 main.py main.py```

```
Traceback (most recent call last):                                           
  File "main.py", line 490, in <module>                                      
    ui.wrapper(main)                                                         
  File "/home/pi/suplemon/ui.py", line 20, in wrapper                        
    curses.wrapper(func)                                                     
  File "/usr/lib/python3.2/curses/wrapper.py", line 43, in wrapper           
    return func(stdscr, *args, **kwds)                                       
  File "main.py", line 486, in main                                          
    app.run()                                                                
  File "main.py", line 97, in run                                            
    self.load()                                                              
  File "main.py", line 86, in load                                           
    self.ui.load()                                                           
  File "/home/pi/suplemon/ui.py", line 90, in load                           
    curses.curs_set(0)                                                       
_curses.error: curs_set() returned ERR
```

**Comment by shakna-israel** [comment]
Seems fixed on ```dev``` branch.

**Comment by richrd** [comment]
Hi, thanks for the report! :+1: 
You're right, the dev branch has a fix, which just try/excepts the error (since the method only hides the default cursor)

I'll be pushing this to master when I review my changes.
